export const data = [
    { title: "My first Post title", description: "My first Post My first PostMy first PostMy first Post My first Post My first PostMy first PostMy first PostMy first Post My first PostMy first PostMy first Post ", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post My first PostMy first PostMy first Post ", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
    { title: "My first Post title", description: "My first Post description", },
]
export const colors = [
    { color: "#fd99ff", id: 1 },
    { color: "#91f48f", id: 2 },
    { color: "#fff599", id: 3 },
    { color: "#9effff", id: 4 },
    { color: "#b69cff", id: 5 },
]